import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`  ${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-blue-50 via-white to-blue-50 shadow-md sticky top-0 z-50 w-full border-b border-gray-200  `}
      >
        <div className="flex flex-col min-h-screen transition-colors duration-500  dark:bg-gray-900 dark:text-gray-100 bg-gray-50 text-gray-800">
          <ThemeProvider
            attribute="class" // Utilise une classe CSS "dark" sur <html>
            defaultTheme="system" // Suivre le thème du système par défaut
            enableSystem={true} // Autorise le thème auto
          >
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
